### ISSUE TITLE
Opportunity/complication icons appearing when they shouldn't with advantage/disadvantage

### ISSUE THREAD

**Issue by chibirobin** [the-metalworks/cosmere-rpg#125]
When messing around with attack rolls with advantage and disadvantage, if you get the highest/lowest number on the discarded die the result will still display it as an opportunity or a complication.

1. Make an attack roll with advantage or disadvantage.
2. If the roll will keep highest, get the other die to roll a 1. If the roll will keep lowest get the other die to be a 20.

I would expect if the result is not a critical fail or success to not display an opportunity or complication.

![weufbwkefbwkefjb](https://github.com/user-attachments/assets/a5039acc-d7ce-41b1-9e6f-e5f6768cad8b)
![Screenshot 2024-10-28 210422](https://github.com/user-attachments/assets/385fc810-d3a2-4b9d-b435-c93a851f8539)

**Version**  
0.1.1

**Comment by zithith** [comment]
Consider waiting on #107 ?

**Comment by MangoFVTT** [comment]
This is fixed by the styling ticket since chat cards now properly show both dice in an advantage/disadvantage roll, so the complications/opportunities will appropriately be faded out if they belong to the dice that caused them.

![Image](https://github.com/user-attachments/assets/c7eb5c11-cc31-4dd4-a831-de96799540f3)
