### ISSUE TITLE
New Goals Add fails

### ISSUE THREAD

**Issue by Doc-Sun** [the-metalworks/cosmere-rpg#159]
**Describe the bug**  
Add new goal button does not work

**To Reproduce**  
_Steps to reproduce the behavior:_
1. _Go to actor sheet
2. _Click on + Add new goal
3. _ new goal does not appear

**Expected behavior**  
_new goal should appear to be editable to add a new goal.

**Foundry VTT Version**  
12.331

**Cosmere RPG System Version**  
0.2.0

**Browser**  
Chrome

**Additional context**  
first identified by @dr.redbeard on Metalworks Discord. Test confirmed by me. 

**Checklist:**
- [ ] I have searched the existing issues to ensure this bug has not already been reported

**Comment by lattaai13** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the onAddGoal method to correctly create a new goal item and render the sheet. Also added error handling and notifications.

You can review changes in this commit: https://github.com/lattaai13/the-metalworks-cosmere-rpg-159/commit/697604ebe52bece034d8b26e12a87ff8a11fa263.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
