### ISSUE TITLE
Actor skill list not being fed skills from config

### ISSUE THREAD

**Issue by Khunkurisu** [the-metalworks/cosmere-rpg#177]
**Describe the bug**  
When using registerSkill, skills are registered properly (to config) but the actor does not have access to them. This results in a bugged skill display and a failure to roll the skill (as it is undefined in the actor).

**To Reproduce**  
_Steps to reproduce the behavior:_
1. Register a skill with registerSkill in the ready hook and make sure `core: true` is set in the skill object.
2. Try to use the skill from the sheet.

**Expected behavior**  
The skill should show up in the sheet with proper formatting and be rollable.

**Screenshots**  
_If applicable, add screenshots to help explain your problem._

**Foundry VTT Version**  
Tested on v12 build 331

**Cosmere RPG System Version**  
Tested on v0.2.0 and v0.2.1

**Browser**  
Local install of Foundry for testing so far.

**Checklist:**
- [x] I have searched the existing issues to ensure this bug has not already been reported

**Comment by MangoFVTT** [comment]
Some additional info from a cursory glance:
- The skill does not exist in `actor.system.skills`. Probably this is because that object is generated by defineSchema() which I think is only called once at the start?
- During my tests, opening the actor sheet fails as well, with the same error inside getRollData(), so it's not restricted to just trying to roll the skill

**Comment by Khunkurisu** [comment]
Turns out the issue is hooking needs to happen in init rather than ready. So not a bug just an error in the documentation from Discord (which has been fixed), so closing this.
